version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4 # [1] Specify version
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # [2] Memory allocation
      #- ELASTIC_PASSWORD=changeme # [3] Set password
      - xpack.security.enabled=false  # <-- Disable security features
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4 # [1] Match ES version
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # [4] ES address (http -> https)
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlLWFjY291bnQ6b3A3dXRuWGxTa1dWY2ttTmwycjROQQ
      #- ELASTICSEARCH_USERNAME=elastic
      #- ELASTICSEARCH_PASSWORD=changeme
      #- ELASTICSEARCH_SSL_VERIFICATIONMODE=none # Skip certificate verification for self-signed certificates
    ports:
      - "5601:5601"
    depends_on: # [5] Start Kibana after ES is running
      - elasticsearch

volumes:
  esdata: